### ISSUE TITLE
java.lang.RuntimeException: Error when enabling iframe communication

### ISSUE THREAD

**Issue by helo1234567** [dequelabs/axe-core-maven-html#369] opened 2023-10-08 17:07 UTC
some times my test cases are failed and give me this error. with 4.8.0 version .
Below is the complete error
java.lang.RuntimeException: Error when enabling iframe communication

	at com.deque.html.axecore.selenium.AxeBuilder.analyzePre43x(AxeBuilder.java:814)
	at com.deque.html.axecore.selenium.AxeBuilder.analyzeRawContext(AxeBuilder.java:654)
	at com.deque.html.axecore.selenium.AxeBuilder.analyze(AxeBuilder.java:610)
	at com.vaf.web.UIManager.excludingSpecificElement(UIManager.java:1443)
	at com.vaf.steps.UISteps.excluding_element(UISteps.java:113)
	at ✽.Check for accessibility issues of 'Landing page2' by excluding this element "input[id='address1-localization-e15523b5bddesktop']"(file:src/test/resources/features/ui/SpectrumUIBuyFlow.feature:37)
Caused by: org.openqa.selenium.JavascriptException: javascript error: axe is not defined

And Below is my code 
 Results axeResult = new AxeBuilder().analyze(driver);

        // Check if the page has accessibility violations
        if (!axeResult.violationFree()) {
            String filePath = "Reports/Accessibility/" + pageName + ".html";
            createDirectoryIfNotExists(filePath);

            // Build the custom report
            String customReport = buildCustomReport(axeResult);

            // Save the report to the specified HTML file
            writeReportToFile(customReport, filePath);

            // Assert that there are no accessibility violations
            Assertions.assertTrue(axeResult.violationFree(), buildCustomReport(axeResult));

            System.out.println("Accessibility report has been written to " + filePath);
        }

**Comment by AdnoC** [comment] 2023-10-27 13:26
Hi. Are you sure you are using version 4.8.0? The code path the error occurs on should not be taken with the code you provided. Additionally, could you provide the URL you were testing? I was unable to replicate your error.

**Comment by dequejenn** [comment] 2023-11-03 12:43
@helo1234567 - we are unable to reproduce. Can you respond to the comment above and give more detail? If we don't get a response by 11/10 we will close this ticket.

**Closed** 2023-11-13 15:02 UTC
Labels: TYPE: user bug, PRIORITY: critical, blocked, in sprint
